import { create } from 'zustand';
import apiClient from '../utils/apiClient';
import { API_URL } from '../config/api';
export interface CartItem {
    _id: string; // The specific line item ID in cart (often generated by Mongoose subdocument)
    product: {
        _id: string;
        name: string;
        images: string[];
        pricing: {
            originalPrice: number;
            sellingPrice: number;
            discountPercentage: number;
        };
        inventory: {
            quantity: number;
            inStock: boolean;
        };
        shop: {
            _id: string;
            name: string;
            slug: string;
        };
    };
    quantity: number;
    price: number;
    variant?: string;
    total: number;
}

export interface Cart {
    _id: string;
    items: CartItem[];
    subtotal: number;
    tax: number;
    shippingCost: number;
    total: number;
    discount: number;
    coupon?: {
        code: string;
        discount: number;
        discountType: string;
    };
}

interface CartState {
    cart: Cart | null;
    isLoading: boolean;
    error: string | null;

    fetchCart: () => Promise<void>;
    addToCart: (productId: string, quantity?: number, variant?: string) => Promise<boolean>;
    updateCartItem: (itemId: string, quantity: number) => Promise<void>;
    removeFromCart: (itemId: string) => Promise<void>;
    clearCart: () => Promise<void>;
    applyCoupon: (code: string) => Promise<boolean>;
    removeCoupon: () => Promise<void>;
    itemCount: () => number;
}

export const useCartStore = create<CartState>((set, get) => ({
    cart: null,
    isLoading: false,
    error: null,

    fetchCart: async () => {
        set({ isLoading: true, error: null });
        try {
            const response = await apiClient.get(`${API_URL}/cart`);
            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
            } else {
                set({ isLoading: false, error: 'Failed to load cart' });
            }
        } catch (error: any) {
            set({ isLoading: false, error: 'Failed to load cart' });
        }
    },

    addToCart: async (productId: string, quantity = 1, variant) => {
        set({ isLoading: true, error: null });
        try {
            const response = await apiClient.post(
                `${API_URL}/cart/add`,
                { productId, quantity, variant }
            );

            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
                return true;
            }
            return false;
        } catch (error: any) {
            set({ isLoading: false, error: error.response?.data?.message || 'Failed to add item' });
            return false;
        }
    },

    updateCartItem: async (itemId: string, quantity: number) => {
        // Optimistic update could be complex due to re-calc on backend, so we'll wait for server
        set({ isLoading: true });
        try {
            const response = await apiClient.patch(
                `${API_URL}/cart/update/${itemId}`,
                { quantity }
            );

            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
            }
        } catch (error: any) {
            set({ isLoading: false, error: error.response?.data?.message || 'Failed to update item' });
        }
    },

    removeFromCart: async (itemId: string) => {
        set({ isLoading: true });
        try {
            const response = await apiClient.delete(`${API_URL}/cart/remove/${itemId}`);

            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
            }
        } catch (error: any) {
            set({ isLoading: false, error: 'Failed to remove item' });
        }
    },

    clearCart: async () => {
        set({ isLoading: true });
        try {
            const response = await apiClient.delete(`${API_URL}/cart/clear`);

            if (response.data?.success) {
                set({ cart: null, isLoading: false }); // or empty cart object
                // Re-fetch to be safe with clean state or just null it
                await get().fetchCart();
            }
        } catch (error: any) {
            set({ isLoading: false, error: 'Failed to clear cart' });
        }
    },

    applyCoupon: async (code: string) => {
        set({ isLoading: true, error: null });
        try {
            const response = await apiClient.post(
                `${API_URL}/cart/apply-coupon`,
                { code }
            );

            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
                return true;
            }
            return false;
        } catch (error: any) {
            set({ isLoading: false, error: error.response?.data?.message || 'Invalid coupon' });
            return false;
        }
    },

    removeCoupon: async () => {
        set({ isLoading: true });
        try {
            const response = await apiClient.delete(`${API_URL}/cart/remove-coupon`);

            if (response.data?.success) {
                set({ cart: response.data?.data?.cart, isLoading: false });
            }
        } catch (error: any) {
            set({ isLoading: false, error: 'Failed to remove coupon' });
        }
    },

    itemCount: () => {
        const { cart } = get();
        if (!cart || !cart.items) return 0;
        return cart.items.reduce((total, item) => total + item.quantity, 0);
    }
}));
